name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk@v3
        with:
          github_user_name: dmsherazi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: endbug/add-and-commit@v9
        with:
          message: "Update github-contribution-grid-snake.svg"
          add: "dist/github-contribution-grid-snake*.svg"
          branch: output
          committer_name: GitHub Actions
          committer_email: actions@github.com

